package juego;

import java.awt.EventQueue;
import juego.estados.Game;


/*
 * CLASE PRINCIPAL, EJECUTA NUESTRA APLICACION. LAUNCHER DEL JUEGO.
 * 
 * */

public class Tets {

	public static void main(String args[]){
		// AGREGAMOS NUESTRA APLICACION A LA COLA DE PROCESOS DE JAVA, ESTO ES UNA BUENA IDEA CUANDO MANEJAMOS INTERFACES GRAFICAS DE USUARIO,
		// YA QUE TODOS LOS EVENTOS PRODUCEN PROCESOS EN JAVA Y ESTO EVITA CONFLICTOS ENTRE ELLOS.
		EventQueue.invokeLater(
			// CREAMOS UN PROCESO QUE EJECUTARA NUESTRA APLICACION.
			new Runnable() {
				// METODO QUE EJECUTARA NUESTA APLICACION
				public void run() {
					new Game(384, 305,"Hola"); // LLAMAMOS A NUESTRO OBJETO GAME CLASE PRINCIPAL DE NUESTRA APLICACION. CONTIENE LA VENTANA.
				}
			}
		);
		
	}

}
